### ISSUE TITLE
improve the exercise

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/f-m1-evaluacion-intermedia-lararb#1]
Really cool job @lararb!!!

Here you have some tips to improve the exercise:

//HTML
- [x] Fix the language and the meta title of the page
- [x] Should the `.menu` element be a non-semantics `div` or a rich semantic `nav` (commonly used for our main navigation)
- [x] We need a nav and a ul/li tags for the menu block
- [x] Menu items should be clickable
- [x] Humanize text in `alt` attributes, a sentence describing the linked image may do the trick.
- [x] Move the font CSS before your main CSS
- [x] Class selectors are free, let's use them instead tag selectors 
- [x] Block elements like our main one do not need a width: 100% or width: 100vw property to tell them to do what they are going to do anyway ;)
- [x] Avoid uppercase/capital on HTML texts, and `br` tag we can transform the text with CSS; this way we keep concepts separated, HTML for content, and CSS for styles
- [x] Finish the main title styles: words should jump and the typography is bolder
- [x] The logo is not working on production (Github Pages), it looks like you are using an absolute route, maybe a relative one would fix it ;)
- [x] Write your classes in English!
- [x] Try to improve your commit messages, better in English and using imperative
- [x] Try to use imperative for your commit messages. Ex. - > Fix central text
- [x] Organize your files in folders, you have a guide to help you with that here --> https://books.adalab.es/materiales-front-end-f/modulo-1.-hola-mundo/1_1_intro_a_la_web#notas-finales-sobre-como-organizar-nuestro-proyecto

Let me know if you have any doubts ;)

Go for it!!

**Comment by lararb** [comment]
Thank you so much Carlos!
Finally I did it! :)

**Comment by oneeyedman** [comment]
Super good job, @lararb!

Well done!
